export const SET_USER = 'setUser'
export const LOGOUT = 'logout'
export const SET_TOKEN = 'setToken'
export const SET_AUTO_LOGOUT = 'setAutoLogout'
export const SET_TODAY_WEATHER = 'setTodayWeather'
export const LOADED_TODAY = 'loadedToday'
